/**
 * Originally autogenerated by feeding the context.json file to https://app.quicktype.io/,
 * now hand-maintained. See CHANGELOG.md for the rationale behind TYPE.
 */

/** One per adaptation construct in lib/adaptations/. Adding a fifth needs human sign-off. */
export type DeploymentType = 'cloudfront' | 'self-signed' | 'container-mod-shib' | 'non-public';

export const DEPLOYMENT_TYPES: DeploymentType[] =
  [ 'cloudfront', 'self-signed', 'container-mod-shib', 'non-public' ];

interface ContextBase {
  STACK_ID:           string;
  STACK_DESCRIPTION?: string;
  PREFIXES:           Prefixes;
  ACCOUNT:            string;
  REGION:             string;
  VPC?:               VPC;
  S3PROXY:            S3Proxy;
  WORDPRESS:          Wordpress;
  AUTOSCALING?:       boolean;
  REDIS?:             Redis;
  JOBRUNNER?:         JobRunner;
  TAGS:               Tags;
}

export interface CloudfrontContext extends ContextBase {
  TYPE: 'cloudfront';
  DNS:  CloudfrontDns;
}

export interface ContainerModShibContext extends ContextBase {
  TYPE: 'container-mod-shib';
  DNS:  ContainerModShibDns;
}

export interface SelfSignedContext extends ContextBase {
  TYPE: 'self-signed';
  DNS?: never;
}

/** Not publicly addressable; needs manual work after stack creation. */
export interface NonPublicContext extends ContextBase {
  TYPE: 'non-public';
  DNS?: never;
}

export type IContext =
  | CloudfrontContext
  | ContainerModShibContext
  | SelfSignedContext
  | NonPublicContext;

export interface CloudfrontDns {
  hostedZone:                string;
  /** Set when the zone is in another AWS account: resolve by id instead of by lookup. */
  crossAccountHostedZoneId?: string;
  /** The cluster anchor. Becomes SERVER_NAME, and thence the WordPress install URL. */
  subdomain:                 string;
  /** For the ALB, so it must be in the deployment region — not CloudFront's us-east-1 cert. */
  certificateARN:            string;
  cloudfront:                Cloudfront;
}

export interface ContainerModShibDns {
  hostedZone:                string;
  crossAccountHostedZoneId?: never;
  subdomain?:                string;
  certificateARN:            string;
  cloudfront?:               never;
}

export interface Cloudfront {
  challengeHeaderName: string;
  distributionDomainName?: string;
}

export interface VPC {
  existingVpcId?: string;
}

export interface Redis {
  cacheNodeType?: string,
  /** Engine version to pin. Omit and ElastiCache selects its current default at create time. */
  engineVersion?: string,
  /** Parameter group family. Defaults to `redis7`; must be compatible with the engine version. */
  parameterGroupFamily?: string,
  /** Eviction policy. Defaults to `allkeys-lru`; the ElastiCache default is `volatile-lru`. */
  maxmemoryPolicy?: string,
}

/** Scheduled ephemeral task that drains the site-manager job queue. Omit and no schedule is built. */
export interface JobRunner {
  /**
   * An EventBridge Scheduler expression: `rate(...)` or a six-field `cron(...)`.
   * In environments where the database auto-pauses when idle, a short `rate(...)` can keep it warm
   * and prevent auto-pause, while `cron(...)` can still leave idle windows where auto-pause engages
   * if there is no organic traffic.
   */
  schedule: string;
  /** IANA zone for interpreting a `cron` expression, e.g. `America/New_York`. Defaults to UTC. */
  timeZone?: string;
  /** Build the schedule in the disabled state. Defaults to enabled. */
  enabled?: boolean;
}

export interface Prefixes {
  wordpress: string;
  s3proxy:   string;
  rds:       string;
}

export interface S3Proxy {
  dockerImage:          string;
  bucketUserSecretName: string;
  OLAP:                 string;
  region:               string;
}

export interface Tags {
  Service:   string;
  Function:  string;
  Landscape: string;
  CostCenter?: string;
  Ticket?: string;
}

export interface Wordpress {
  dockerImage: string;
  env:         WordpressEnv;
  secret:      WordpressSecret;
}

export interface WordpressEnv {
  spEntityId?:       string;
  idpEntityId?:      string;
  s3ProxyHost?:      string;
  TZ?:               string;
  dbType?:           WORDPRESS_DB_TYPE;
  dbHost?:           string;
  dbUser?:           string;
  dbName?:           string;
  dbPort?:           string;
  debug?:            any;
  /**
   * Canonical WP_ENVIRONMENT_TYPE signal used by both WordPress runtime behavior
   * and this stack's derived RDS posture (durability, high availability, scaling).
   * Allowed values follow WordPress: 'local' | 'development' | 'staging' | 'production'.
   * See https://developer.wordpress.org/reference/functions/wp_get_environment_type/
   * Values outside this set are treated as 'production' by WordPress core, which can
   * leave non-production containers without robots.txt suppression, making them indexable.
   * BU stage labels (prod/test/devl/syst) belong in TAGS.Landscape, not here.
   */
  environmentType?:  'local' | 'development' | 'staging' | 'production';
}

export interface WordpressSecret {
  wpSecretArn:         string;
  spSecretArn:         string;
  fieldNames:      SecretFieldNames;
}

export interface SecretFieldNames {
  dbPassword:  string;
  configExtra: string;
  spKey?:       string;
  spCert?:      string;
}

export enum WORDPRESS_DB_TYPE {
  INSTANCE = 'instance',
  CLUSTER = 'cluster',
  SERVERLESS = 'serverless'
}
